name: Copy Folder

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/siga-docker-folder-copy.yml'



jobs:
  copy-folder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Folder Structure and Copy
      run: |
        FOLDER_PATH=docker
        if [ ! -d "$FOLDER_PATH" ]; then
          echo "Folder structure does not exist, creating..."
          mkdir -p "$FOLDER_PATH"
          touch "$FOLDER_PATH/README.yml"
        else
          echo "Folder structure already exists."
        fi

        SOURCE_REPO=buerokratt/open-eid-SiGa
        SOURCE_FOLDER=docker

        git clone --branch=develop "https://github.com/$SOURCE_REPO.git" source-repo

        TARGET_DIRECTORY="$FOLDER_PATH"
        mkdir -p "$TARGET_DIRECTORY"

        cp -R "source-repo/$SOURCE_FOLDER/." "$TARGET_DIRECTORY"

    - name: Commit and Push Changes
      run: |
        cd "$FOLDER_PATH"
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Copy folder from another repo"
        git push
